

export const etfs = [
	{
		ticker: 'AKCH',
		type: 'stocks',
		market: 'emerging',
    region: 'china',
    currency: 'rub',
		markets: { emerging: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'AKEU',
		type: 'stocks',
		market: 'developed',
    region: 'europe',
    currency: 'eur',
		markets: { developed: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'AKME',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'AKNX',
		type: 'stocks',
		market: 'usa',
    sector: 'IT',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'AKSP',
		type: 'stocks',
		market: 'usa',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'VTBA',
		type: 'stocks',
		market: 'usa',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'VTBE',
		type: 'stocks',
		market: 'emerging',
    currency: 'usd',
		markets: { emerging: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'VTBX',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'DIVD',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'ESGR',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'SBMX',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'SBSP',
		type: 'stocks',
		market: 'usa',
    currency: 'rub',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'TBIO',
		type: 'stocks',
		market: 'usa',
    sector: 'biotech',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'TECH',
		type: 'stocks',
		market: 'usa',
    sector: 'tech',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'TIPO',
		type: 'stocks',
		market: 'usa',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'TMOS',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'TSPX',
		type: 'stocks',
		market: 'usa',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXCN',
		type: 'stocks',
		market: 'emerging',
    region: 'china',
    currency: 'rub',
		markets: { emerging: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXDE',
		type: 'stocks',
		market: 'developed',
    region: 'Germany',
    currency: 'rub',
		markets: { developed: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXDM',
		type: 'stocks',
		market: 'developed',
    currency: 'rub',
		markets: { developed: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXIM',
		type: 'stocks',
		market: 'usa',
    sector: 'IT',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXIT',
		type: 'stocks',
		market: 'usa',
    sector: 'IT',
    currency: 'rub',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXKZ',
		type: 'stocks',
		market: 'emerging',
    region: 'Kazahstan',
    currency: 'rub',
		markets: { emerging: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXRL',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXRW',
		type: 'stocks',
		market: 'global',
    currency: 'rub',
		markets: { global: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXUS',
		type: 'stocks',
		market: 'usa',
    currency: 'rub',
		markets: { usa: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'FXWO',
		type: 'stocks',
		market: 'global',
    currency: 'rub',
		markets: { global: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'RUSE',
		type: 'stocks',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 },
	},
	{
		ticker: 'VTBG',
		type: 'gold',
		market: '',
    currency: 'rub',
		markets: { gold: 100 },
		actives: { gold: 100 },
	},
	{
		ticker: 'TGLD',
		type: 'gold',
		market: '',
    currency: 'usd',
		markets: { gold: 100 },
		actives: { gold: 100 },
	},
	{
		ticker: 'FXGD',
		type: 'gold',
		market: '',
    currency: 'rub',
		markets: { gold: 100 },
		actives: { gold: 100 },
	},
	{
		ticker: 'AKMB',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'VTBB',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'VTBH',
		type: 'bonds',
		market: 'usa',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'VTBM',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'VTBU',
		type: 'bonds',
		market: 'russia',
    currency: 'usd',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'SBCB',
		type: 'bonds',
		market: 'russia',
    currency: 'usd',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'SBGB',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'SBRB',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'FXMM',
		type: 'bonds',
		market: 'usa',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'FXRB',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'FXRU',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'FXTB',
		type: 'bonds',
		market: 'usa',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'RUSB',
		type: 'bonds',
		market: 'russia',
    currency: 'rub',
		markets: { russia: 100 },
		actives: { bonds: 100 },
	},
	{
		ticker: 'TEUR',
		type: 'mixed',
		market: 'developed',
    region: 'europe',
    currency: 'eur',
		markets: { developed: 100 },
		actives: { stocks: 25, bonds: 50, gold: 25 },
	},
	{
		ticker: 'TRUR',
		type: 'mixed',
		market: 'russia',
    currency: 'rub',
		markets: { usa: 100 },
		actives: { stocks: 25, bonds: 50, gold: 25 },
	},
	{
		ticker: 'TUSD',
		type: 'mixed',
		market: 'usa',
    currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 25, bonds: 50, gold: 25 },
	},
	{
		ticker: 'AMIN',
		type: 'stocks',
		market: 'global',
		currency: 'usd',
		markets: { global: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMGM',
		type: 'stocks',
		market: 'gold',
		currency: 'usd',
		markets: { gold: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMSL',
		type: 'stocks',
		market: 'gold',
		currency: 'usd',
		markets: { gold: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMEM',
		type: 'stocks',
		market: 'emerging',
		currency: 'usd',
		markets: { emerging: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMCC',
		type: 'stocks',
		market: 'global',
		currency: 'usd',
		markets: { global: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMVF',
		type: 'stocks',
		market: 'usa',
		currency: 'usd',
		markets: { usa: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'TSPV',
		type: 'stocks',
		market: 'global',
		currency: 'usd',
		markets: { global: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'FXFA',
		type: 'stocks',
		market: 'global',
		currency: 'rub',
		markets: { global: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMRE',
		type: 'stocks',
		market: 'russia',
		currency: 'rub',
		markets: { russia: 100 },
		actives: { stocks: 100 }
	},
	{
		ticker: 'AMSC',
		type: 'stocks',
		market: 'usa',
		currency: 'usd',
		markets: { usd: 100 },
		actives: { stocks: 100 }
	}
];
